// 100 Danish child-friendly words with emoji for the secret word generator
const WORDS: { word: string; emoji: string }[] = [
  { word: 'Hus', emoji: '🏠' },
  { word: 'Mus', emoji: '🐭' },
  { word: 'Kat', emoji: '🐱' },
  { word: 'Elefant', emoji: '🐘' },
  { word: 'Solsikke', emoji: '🌻' },
  { word: 'Regnbue', emoji: '🌈' },
  { word: 'Sommerfugl', emoji: '🦋' },
  { word: 'Is', emoji: '🍦' },
  { word: 'Kage', emoji: '🎂' },
  { word: 'Ballon', emoji: '🎈' },
  { word: 'Robot', emoji: '🤖' },
  { word: 'Dinosaur', emoji: '🦕' },
  { word: 'Prinsesse', emoji: '👸' },
  { word: 'Drage', emoji: '🐉' },
  { word: 'Pirat', emoji: '🏴‍☠️' },
  { word: 'Æble', emoji: '🍎' },
  { word: 'Banan', emoji: '🍌' },
  { word: 'Jordbær', emoji: '🍓' },
  { word: 'Tog', emoji: '🚂' },
  { word: 'Bil', emoji: '🚗' },
  { word: 'Cykel', emoji: '🚲' },
  { word: 'Fly', emoji: '✈️' },
  { word: 'Raket', emoji: '🚀' },
  { word: 'Skib', emoji: '🚢' },
  { word: 'Traktor', emoji: '🚜' },
  { word: 'Hund', emoji: '🐶' },
  { word: 'Kanin', emoji: '🐰' },
  { word: 'Fisk', emoji: '🐟' },
  { word: 'Fugl', emoji: '🐦' },
  { word: 'Frø', emoji: '🐸' },
  { word: 'Slange', emoji: '🐍' },
  { word: 'Edderkop', emoji: '🕷️' },
  { word: 'Bi', emoji: '🐝' },
  { word: 'Ko', emoji: '🐄' },
  { word: 'Gris', emoji: '🐷' },
  { word: 'Hest', emoji: '🐴' },
  { word: 'Giraf', emoji: '🦒' },
  { word: 'Løve', emoji: '🦁' },
  { word: 'Abe', emoji: '🐵' },
  { word: 'Pingvin', emoji: '🐧' },
  { word: 'Snemand', emoji: '⛄' },
  { word: 'Juletræ', emoji: '🎄' },
  { word: 'Stjerne', emoji: '⭐' },
  { word: 'Måne', emoji: '🌙' },
  { word: 'Sol', emoji: '☀️' },
  { word: 'Sky', emoji: '☁️' },
  { word: 'Blomst', emoji: '🌸' },
  { word: 'Træ', emoji: '🌳' },
  { word: 'Bjerg', emoji: '⛰️' },
  { word: 'Vulkan', emoji: '🌋' },
  { word: 'Slot', emoji: '🏰' },
  { word: 'Telt', emoji: '⛺' },
  { word: 'Bro', emoji: '🌉' },
  { word: 'Fyr', emoji: '🔥' },
  { word: 'Kirke', emoji: '⛪' },
  { word: 'Klovn', emoji: '🤡' },
  { word: 'Troldmand', emoji: '🧙' },
  { word: 'Heks', emoji: '🧙‍♀️' },
  { word: 'Spøgelse', emoji: '👻' },
  { word: 'Havfrue', emoji: '🧜‍♀️' },
  { word: 'Ninja', emoji: '🥷' },
  { word: 'Cowboy', emoji: '🤠' },
  { word: 'Astronaut', emoji: '🧑‍🚀' },
  { word: 'Brandmand', emoji: '🧑‍🚒' },
  { word: 'Superhelt', emoji: '🦸' },
  { word: 'Guitar', emoji: '🎸' },
  { word: 'Tromme', emoji: '🥁' },
  { word: 'Trompet', emoji: '🎺' },
  { word: 'Klaver', emoji: '🎹' },
  { word: 'Mikrofon', emoji: '🎤' },
  { word: 'Fodbold', emoji: '⚽' },
  { word: 'Skateboard', emoji: '🛹' },
  { word: 'Svømmer', emoji: '🏊' },
  { word: 'Skiløber', emoji: '⛷️' },
  { word: 'Boksning', emoji: '🥊' },
  { word: 'Pizza', emoji: '🍕' },
  { word: 'Hamburger', emoji: '🍔' },
  { word: 'Hotdog', emoji: '🌭' },
  { word: 'Popcorn', emoji: '🍿' },
  { word: 'Slik', emoji: '🍬' },
  { word: 'Paraply', emoji: '☂️' },
  { word: 'Briller', emoji: '👓' },
  { word: 'Hat', emoji: '🎩' },
  { word: 'Sko', emoji: '👟' },
  { word: 'Krone', emoji: '👑' },
  { word: 'Saks', emoji: '✂️' },
  { word: 'Hammer', emoji: '🔨' },
  { word: 'Nøgle', emoji: '🔑' },
  { word: 'Lommelygte', emoji: '🔦' },
  { word: 'Kompas', emoji: '🧭' },
  { word: 'Krokodille', emoji: '🐊' },
  { word: 'Ugle', emoji: '🦉' },
  { word: 'Delfin', emoji: '🐬' },
  { word: 'Haj', emoji: '🦈' },
  { word: 'Blæksprutte', emoji: '🐙' },
  { word: 'Snegl', emoji: '🐌' },
  { word: 'Mariehøne', emoji: '🐞' },
  { word: 'Panda', emoji: '🐼' },
  { word: 'Papegøje', emoji: '🦜' },
  { word: 'Flamingo', emoji: '🦩' },
];

export interface RandomWord {
  word: string;
  emoji: string;
}

export function getRandomWord(): RandomWord {
  const entry = WORDS[Math.floor(Math.random() * WORDS.length)];
  return { word: entry.word, emoji: entry.emoji };
}
